### ISSUE TITLE
Page about example bots

### ISSUE THREAD

**Issue by ghost** [deltachat-bot/bot-pages#11]
- To report bugs please open issues in the corresponding code repositories
- You may also copy and adapt them, if that suits you! They're mostly licensed under the GPL, which allows you to use the code, and also to change it as long as you re-publish your result (at least on request).
- List of bots, short description

**Comment by ghost** [comment]
Which bots are good examples to build upon? afaict:

* [echo](https://github.com/deltachat-bot/echo)
* [deltabot](https://github.com/deltachat-bot/deltabot)
* [public groups](https://github.com/deltachat-bot/public-groups-bot)
* oauth2 bot

Useful libraries?

* https://github.com/deltachat-bot/deltachat-node-webbot-base
* https://github.com/deltachat-bot/deltachat-node-bot-base

**Comment by pabzm** [comment]
I think the development page should present the libraries and the clean echo bots as building blocks. An echo bot is not something to run but to look at and maybe use as extendable basis, I'd say.

The practically usable bots (deltabot, public-groups, oauth) should in my opinion be presented in the forum, not on the development page.

**Comment by ghost** [comment]
Good point.
