### ISSUE TITLE
Beautify pages

### ISSUE THREAD

**Issue by pabzm** [deltachat-bot/bot-pages#2]
These pages should stay simple and clear, but they still need some love. E.g. the header, the link color, maybe the menu.

- [x] mobile-optimized #16 
- [x] code blocks
- [x] link color
- [x] syntax highlighting for code blocks #19 
- [ ] colors!
- [x] bulma redesign #27

**Comment by ghost** [comment]
Cool, I'm quite happy with the results :) Other ideas what we could do to make the page even prettier?

On IRC, @pabzm mentioned something about more colors. Not sure if we really need more colors, but one possibility would be a color gradient as on https://autocrypt.org, maybe in a soft orange, and only at the sides?

**Comment by ghost** [comment]
> Um, I'm not a fan of color gradients, to be honest.
> 
> Me asking for more colours was rather targeting text-and logo-colors, together with a general overhaul of font-selection, layout proportions, etc. Not being more colourful for the sake of it.
> 
> Sorry I wasn't clearer before!

_Originally posted by @pabzm in https://github.com/deltachat-bot/bot-pages/pull/22#issuecomment-590884783_

**Comment by ghost** [comment]
After #30, is there much more needed to close this issue?
