### ISSUE TITLE
broken link to example bot

### ISSUE THREAD

**Issue by ghost** [deltachat-bot/bot-pages#31]
The link here is broken: https://github.com/deltachat-bot/bot-pages/blame/master/development.md#L69

the file was renamed, and now doesn't have 110 lines anymore either, so not sure which example we need to find. The file is now here: https://github.com/deltachat-bot/deltabot/blob/master/simplebot/cmdline.py

we could point to a specific commit instead of master here.

**Comment by pabzm** [comment]
We should probably remove that link, because the python bindings changed and the example bot works differently now. I'll take care of it, thanks for noticing!
